import { MetadataRoute } from "next";

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://novakou.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/explorer",
          "/formation/*",
          "/produit/*",
          "/mentors",
          "/mentors/*",
          "/instructeurs",
          "/instructeurs/*",
          "/boutique/*",
          "/tarifs",
          "/affiliation",
          "/a-propos",
          "/contact",
          "/faq",
          "/aide",
          "/partenaires",
          "/cgu",
          "/confidentialite",
          "/cookies",
        ],
        disallow: [
          "/dashboard",
          "/dashboard/*",
          "/client",
          "/client/*",
          "/agence",
          "/agence/*",
          "/admin",
          "/admin/*",
          "/admin-login/*",
          "/backoffice/*",
          "/mentor",
          "/mentor/*",
          "/vendeur",
          "/vendeur/*",
          "/apprenant",
          "/apprenant/*",
          "/affilie",
          "/affilie/*",
          "/wallet",
          "/wallet/*",
          "/kyc",
          "/2fa",
          "/checkout",
          "/checkout/*",
          "/payment",
          "/payment/*",
          "/messages",
          "/messages/*",
          "/api",
          "/api/*",
          "/maintenance",
        ],
      },
      // Generative AI crawlers — opt-in to GenAI training + citations.
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "ChatGPT-User", allow: "/" },
      { userAgent: "ClaudeBot", allow: "/" },
      { userAgent: "anthropic-ai", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "Google-Extended", allow: "/" },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
    host: BASE_URL,
  };
}
