/**
 * Guides proposés en fin d'article (« À lire ensuite »).
 *
 * Reflet du tableau GUIDES de app/(formations)/guides/page.tsx — même
 * principe que OldGuideJsonLd : à tenir synchronisé si un titre ou un
 * résumé change sur l'index. Un guide absent d'ici ne casse rien : il ne
 * sera simplement pas proposé.
 */

export type GuideLie = {
  href: string;
  titre: string;
  resume: string;
  categorie: string;
  duree: string;
  /** Icône Material Symbols (déjà dans le sous-ensemble chargé). */
  icone: string;
};

export const GUIDES_LIES: GuideLie[] = [
  { href: "/guides/page-de-vente-qui-convertit", titre: "Créer une page de vente qui convertit", resume: "Structure, copywriting et exemples : accroche, preuve sociale, offre, garantie, appel à l'action. Le pas-à-pas pour transformer vos visiteurs en acheteurs et brancher le paiement Mobile Money.", categorie: "Vendre", duree: "16 min", icone: "ads_click" },
  { href: "/guides/order-bump-upsell-augmenter-panier", titre: "Order bump, upsell & down-sell : augmenter son panier moyen", resume: "Le vrai levier de revenu n'est pas plus de trafic mais un panier plus élevé. Order bump, upsell, down-sell : quoi proposer, à quel prix, et comment le mettre en place dans votre tunnel Novakou.", categorie: "Vendre", duree: "15 min", icone: "trending_up" },
  { href: "/guides/vendre-ebook-en-afrique", titre: "Vendre un ebook en Afrique : de l'écriture à la première vente", resume: "Le produit numérique idéal pour débuter : trouver un sujet qui se vend, écrire vite, créer une couverture, fixer son prix en FCFA, publier sur Novakou et encaisser en Mobile Money.", categorie: "Créer", duree: "15 min", icone: "menu_book" },
  { href: "/guides/vendre-coaching-en-ligne", titre: "Vendre du coaching en ligne : offres, prix et process", resume: "L'offre la plus rentable : définir son accompagnement, fixer un prix premium et le justifier, gérer le process de A à Z (paiement Mobile Money, séances visio, suivi) et monter une offre en escalier.", categorie: "Vendre", duree: "16 min", icone: "psychology" },
  { href: "/guides/abonnement-membership-revenus-recurrents", titre: "Abonnement & membership : bâtir des revenus récurrents", resume: "Le revenu récurrent est le Graal : communauté privée, contenu mensuel, club. Modèles, prix en FCFA, paiements récurrents Mobile Money et surtout la rétention pour ne pas voir vos membres partir.", categorie: "Vendre", duree: "16 min", icone: "autorenew" },
  { href: "/guides/lancer-pub-tiktok-produits-digitaux", titre: "Lancer une publicité TikTok pour vendre ses produits digitaux", resume: "Créer une pub TikTok qui vend en Afrique : accroche 3 secondes, format natif, ciblage, budget réaliste en FCFA, pixel TikTok et envoi du trafic vers un lien de paiement ou un tunnel Novakou.", categorie: "Promouvoir", duree: "16 min", icone: "music_note" },
  { href: "/guides/installer-pixel-facebook-tiktok", titre: "Installer un pixel Facebook, TikTok, Snapchat & Pinterest", resume: "Le guide complet du pixel de suivi : récupérer son ID sur chaque plateforme, le poser nativement sur toutes ses pages Novakou, suivre les conversions et créer des audiences de reciblage.", categorie: "Promouvoir", duree: "14 min", icone: "track_changes" },
  { href: "/guides/moyens-paiement-en-ligne-afrique", titre: "Les moyens de paiement en ligne en Afrique : le guide 2026", resume: "Mobile Money (Wave, Orange, MTN, Moov), carte bancaire, agrégateurs : le panorama complet des moyens de paiement en Afrique francophone, par pays, et ce qu'il faut accepter pour vendre.", categorie: "Vendre", duree: "15 min", icone: "account_balance_wallet" },
  { href: "/guides/vendre-partout-avec-lien-de-paiement", titre: "Vendre partout avec un lien de paiement", resume: "L'outil le plus simple pour vendre sur WhatsApp, en bio, dans une pub ou sur votre site : page produit ou paiement direct, redirection après achat et webhook signé pour débloquer l'accès.", categorie: "Vendre", duree: "14 min", icone: "link" },
  { href: "/guides/automatiser-sa-boutique", titre: "Automatiser sa boutique : workflows, e-mails et relances", resume: "Gagner du temps et ne perdre aucune vente : e-mail de bienvenue, relance de panier abandonné, upsell, séquences déclenchées. Mettez en place vos premiers workflows Novakou pas à pas.", categorie: "Automatiser", duree: "15 min", icone: "smart_toy" },
  { href: "/guides/novakou-fonctionnalites-completes", titre: "Toutes les fonctionnalités de Novakou", resume: "Boutique, Mobile Money, tunnel de vente, automatisation, affiliation, pixels, escrow, abonnements, IA : le tour complet de la plateforme n°1 de vente de produits numériques en Afrique.", categorie: "Vendre", duree: "13 min", icone: "auto_awesome" },
  { href: "/guides/meilleures-plateformes-vendre-produits-digitaux-afrique", titre: "Meilleures plateformes pour vendre des produits digitaux en Afrique", resume: "Comparatif 2026 : Mobile Money, frais, tunnel, sécurité. Pourquoi Novakou est la plateforme n°1 pour vendre vos formations et produits numériques en Afrique francophone.", categorie: "Vendre", duree: "12 min", icone: "storefront" },
  { href: "/guides/top-20-produits-digitaux-rentables-2026", titre: "Top 20 des produits digitaux rentables à lancer en 2026", resume: "20 idées concrètes de produits numériques à lancer en Afrique en 2026, avec fourchettes de prix en FCFA, cible et raison de vente. De l'ebook au coaching en passant par les templates et les prompts IA.", categorie: "Créer", duree: "16 min", icone: "lightbulb" },
  { href: "/guides/novakou-vs-systeme-io", titre: "Novakou vs Systeme.io : lequel choisir en Afrique ?", resume: "Comparatif honnête : Mobile Money, frais, tunnel, escrow, automatisation. Systeme.io excelle sur les tunnels mais n'a pas de Mobile Money natif — Novakou réunit tout pour l'Afrique.", categorie: "Vendre", duree: "15 min", icone: "compare_arrows" },
  { href: "/guides/alternative-systeme-io-afrique", titre: "La meilleure alternative à Systeme.io en Afrique (Mobile Money)", resume: "Pourquoi Systeme.io ne suffit pas en Afrique et ce qu'il faut exiger d'une alternative : Mobile Money, gratuit pour démarrer, tunnel, escrow, automatisation. Comment migrer en 30 secondes.", categorie: "Vendre", duree: "14 min", icone: "swap_horiz" },
  { href: "/guides/creer-produit-numerique-afrique", titre: "Créer son produit numérique en Afrique : le guide complet 2026", resume: "De l'idée à la première vente : trouver son idée, choisir le type de produit, le créer au smartphone, fixer son prix en FCFA, publier sur Novakou et vendre en Mobile Money.", categorie: "Créer", duree: "16 min", icone: "rocket_launch" },
  { href: "/guides/meilleures-niches-produits-digitaux-afrique", titre: "Les 10 meilleures niches pour vendre des produits digitaux en Afrique", resume: "Quelle niche choisir pour vendre en ligne ? 10 niches porteuses en Afrique francophone, avec exemples de produits, prix FCFA, cible et canal de promotion.", categorie: "Créer", duree: "15 min", icone: "category" },
  { href: "/guides/creer-formation-video-smartphone", titre: "Créer une formation vidéo au smartphone : le guide complet", resume: "Filmer une formation vidéo pro avec un simple smartphone : matériel minimal, structure des leçons, tournage, montage gratuit, prix en FCFA et vente sur Novakou.", categorie: "Créer", duree: "16 min", icone: "videocam" },
  { href: "/guides/vendre-avec-mobile-money-guide", titre: "Vendre en ligne avec le Mobile Money en Afrique", resume: "Wave, Orange Money, MTN, Moov : comment accepter le Mobile Money pour vendre vos produits numériques, le parcours d'achat idéal et les erreurs à éviter.", categorie: "Vendre", duree: "15 min", icone: "smartphone" },
  { href: "/guides/lancer-pub-facebook-instagram-vendre-boutique", titre: "Lancer une publicité Facebook & Instagram pour vendre sa boutique", resume: "Guide pratique pour une pub Meta qui vend en Afrique : pixel, audience, visuel, budget FCFA réaliste, envoi vers un lien de paiement ou un tunnel, et optimisation.", categorie: "Promouvoir", duree: "16 min", icone: "campaign" },
  { href: "/guides/gagner-argent-en-ligne-afrique-2026", titre: "Gagner de l'argent en ligne en Afrique en 2026 : le guide réaliste", resume: "Les vraies façons de gagner de l'argent en ligne en Afrique en 2026, avec un focus sur la vente de produits numériques : modèles, étapes, exemples FCFA et arnaques à éviter.", categorie: "Gagner", duree: "17 min", icone: "savings" },
  { href: "/guides/importer-systeme-io", titre: "Importer son tunnel Systeme.io sur Novakou", resume: "Vous venez de Systeme.io ? Collez l'URL de votre tunnel : titre, texte et image sont importés automatiquement en brouillon. Migration en 30 secondes, captures à l'appui.", categorie: "Technique", duree: "9 min", icone: "download" },
  { href: "/guides/devenir-affilie-gagner-argent", titre: "Devenir affilié Novakou : gagner en recommandant", resume: "Touchez 40 % de commission sur chaque vente générée, sans rien créer. Lien unique, où le partager, validation 14 j, retrait Mobile Money dès 100 FCFA.", categorie: "Gagner", duree: "8 min", icone: "group" },
  { href: "/guides/creer-son-produit", titre: "Comment créer son premier produit digital", resume: "De l'idée à la publication : identifiez votre expertise, structurez votre contenu, produisez avec un smartphone et publiez sur Novakou.", categorie: "Créer", duree: "12 min", icone: "package_2" },
  { href: "/guides/vendre-en-ligne", titre: "Comment vendre ses formations en Afrique", resume: "Pages de vente, tunnels, leviers psychologiques, réseaux sociaux, email marketing, affiliation. Toutes les stratégies qui marchent.", categorie: "Vendre", duree: "15 min", icone: "trending_up" },
  { href: "/guides/guide-complet-novakou", titre: "Le guide complet Novakou : de A à Z", resume: "De l'inscription à votre première vente. Boutique, paiements, tunnels, IA, emails, affiliation, retraits. Tout est couvert.", categorie: "Technique", duree: "20 min", icone: "menu_book" },
  { href: "/guides/trouver-son-idee-de-produit", titre: "Comment trouver son idée de produit digital", resume: "La méthode des 3 cercles, les niches portantes en Afrique, validation gratuite en 48h — de zéro idée à un concept validé.", categorie: "Créer", duree: "10 min", icone: "lightbulb" },
  { href: "/guides/publicite-facebook", titre: "Publicité Facebook pour vendre en Afrique", resume: "Créer des campagnes rentables depuis 2 000 FCFA/jour. Ciblage Afrique francophone, pixel, visuels, optimisation ROAS.", categorie: "Promouvoir", duree: "18 min", icone: "campaign" },
  { href: "/guides/automatisations-novakou", titre: "Automatisations Novakou : vendre pendant que vous dormez", resume: "Séquences de bienvenue, relance panier, certificats automatiques, upsell post-achat — configurez une fois, encaissez toujours.", categorie: "Automatiser", duree: "12 min", icone: "bolt" },
  { href: "/guides/sequences-emails", titre: "Séquences emails qui vendent en automatique", resume: "Lead magnets, séquence de bienvenue en 5 emails, relances, segmentation. 23 templates email inclus sur Novakou.", categorie: "Automatiser", duree: "15 min", icone: "mail" },
  { href: "/guides/description-produit", titre: "Rédiger une description de produit irrésistible", resume: "La structure AIDA, transformer vos modules en bénéfices, le titre parfait, la preuve sociale — avec 3 exemples avant/après.", categorie: "Vendre", duree: "10 min", icone: "edit_note" },
  { href: "/guides/tunnel-de-vente-novakou", titre: "Tunnel de vente sur Novakou : guide pas-à-pas", resume: "Builder drag-and-drop, 30+ blocs, page de capture, page de vente, checkout Mobile Money, upsell, A/B testing.", categorie: "Technique", duree: "15 min", icone: "account_tree" },
  { href: "/guides/mobile-money-encaisser-paiements", titre: "Mobile Money : Wave, Orange, MTN, Moov — guide complet", resume: "Recevoir vos paiements Mobile Money en Afrique : frais réels, délais, configuration en 3 minutes sur Novakou, retraits.", categorie: "Technique", duree: "10 min", icone: "payments" },
  { href: "/guides/fixer-prix-formation", titre: "Combien faire payer ma formation ? Méthode pricing complète", resume: "Tableaux de prix par type de contenu en FCFA. Comment éviter de sous-vendre, justifier un prix premium, prix d'ancrage et upsell.", categorie: "Vendre", duree: "9 min", icone: "sell" },
  { href: "/guides/whatsapp-business-vendre-formations", titre: "WhatsApp Business pour vendre vos formations en Afrique", resume: "Status, catalogue, listes diffusion, groupes communauté. Convertir vos contacts WhatsApp en acheteurs sans paraître spam.", categorie: "Promouvoir", duree: "12 min", icone: "chat" },
  { href: "/guides/instagram-vendre-formations-afrique", titre: "Instagram pour vendre vos formations : stratégie organique", resume: "Bio optimisée, Reels qui convertissent, DM stratégique, hashtags Afrique francophone. 0 budget pub, résultats en 30 jours.", categorie: "Promouvoir", duree: "13 min", icone: "photo_camera" },
  { href: "/guides/affiliation-recruter-affilies", titre: "Recruter des affiliés pour démultiplier vos ventes", resume: "Construire un programme d'affiliation rentable : commission idéale, recrutement, tracking sur Novakou, gestion des paiements.", categorie: "Vendre", duree: "11 min", icone: "group_add" },
  { href: "/guides/tiktok-reels-vendre-formations", titre: "TikTok & Reels : générer 10 000 vues par vidéo", resume: "Hooks qui marchent, format vertical, hashtags Afrique, transformer une vue en clic. Stratégie virale 0 budget.", categorie: "Promouvoir", duree: "12 min", icone: "video_library" },
  { href: "/guides/lancement-30-jours", titre: "Lancer sa formation en 30 jours : checklist actionnable", resume: "Planning jour par jour de l'idée à la 1ère vente. Méthode validée par 100+ créateurs Novakou — 0 capital initial requis.", categorie: "Créer", duree: "16 min", icone: "rocket_launch" },
  { href: "/guides/email-marketing-5-emails-vendent", titre: "Les 5 emails indispensables qui font vendre", resume: "Welcome, valeur, autorité, objection, dernier appel — la séquence éprouvée + 5 templates emails complets prêts à copier.", categorie: "Automatiser", duree: "12 min", icone: "mark_email_read" },
  { href: "/guides/linkedin-personal-branding-expert", titre: "Personal branding LinkedIn pour expert africain", resume: "Profil optimisé, 3 posts par semaine qui marchent, DM commercial sans paraître spammy, convertir followers en acheteurs.", categorie: "Promouvoir", duree: "14 min", icone: "person" },
  { href: "/guides/vendre-diaspora-africaine", titre: "Vendre à la diaspora : encaisser en euros depuis l'Afrique", resume: "Activer paiement carte international, ciblage Facebook France/Belgique/Canada, communauté diaspora, prix multi-devises.", categorie: "Vendre", duree: "11 min", icone: "public" },
  { href: "/guides/scaler-catalogue-produits", titre: "Passer de 1 formation à un catalogue complet (10x revenu)", resume: "Bundles, abonnements, formations complémentaires, ladder de prix. Multiplier le panier moyen et la lifetime value client.", categorie: "Vendre", duree: "13 min", icone: "inventory_2" },
];

/**
 * Trois guides à lire ensuite : même catégorie d'abord, complétés par les
 * premiers guides de l'index. Déterministe (rendu serveur stable).
 */
export function guidesLies(slug: string, categorie: string, nombre = 3): GuideLie[] {
  const autres = GUIDES_LIES.filter((g) => g.href !== `/guides/${slug}`);
  const memeCategorie = autres.filter((g) => g.categorie === categorie);
  const complement = autres.filter((g) => g.categorie !== categorie);
  return [...memeCategorie, ...complement].slice(0, nombre);
}
